services:
  - type: web
    name: road-freight-risk-ui
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port 10000 --server.enableCORS false
    repo: https://github.com/ibrahimlabaranali/road-freight-risk-ai
    branch: main
    rootDir: frontend/streamlit
