services:
  - type: web
    name: road-risk-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.fastapi.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PORT
        value: 10000

  - type: web
    name: road-risk-mobile-frontend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run mobile/streamlit_app_mobile.py --server.port=10001 --server.address=0.0.0.0"
    envVars:
      - key: PORT
        value: 10001
