services:
  - type: web
    name: road-freight-risk-ai-frontend
    env: python
    plan: free
    branch: main
    runtime: python
    buildCommand: ""
    startCommand: streamlit run mobile/streamlit_app_mobile.py --server.port=8501 --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
    buildFilter:
      paths:
        - mobile/**
        - requirements.txt
        - .streamlit/**
    autoDeploy: true
